### ISSUE TITLE
confusion about `sockaddr` in class `net_address` 

### ISSUE THREAD

**Issue by g10906** [YukunJ/Turtle#30]
What if use `sockaddr_storage` instead of `sockaddr` for both IPv4 and IPv6?
Seems  `sockaddr` and `sockaddr_in` are both 16bytes, however `sockaddr_in6` is 28 bytes, would it access illegal address after converting `sockaddr*` into `sockaddr_in6*` for IPv6?

**Comment by YukunJ** [comment]
Yes you are right. `sockaddr_storage` has size of 128 bytes, it should be large enough to contain `sockaddr_in6` (28 bytes) and `sockaddr_in` (16 bytes). The member variable should be of type `sockaddr_storage ` instead of `sockaddr`.

Would you like to make a PR for this issue please?

**Comment by g10906** [comment]
Just replace the class member of type `struct sockaddr` with `struct sockaddr_storage` should be ok, not worth a pr.  :D

**Comment by g10906** [comment]
like this:
```C++
private:
  mutable struct sockaddr_storage addr_ {};
```

And there is another example related to `sockaddr_storage`: https://man.archlinux.org/man/getaddrinfo.3.en#EXAMPLES

**Comment by YukunJ** [comment]
I will do it then. Thanks for pointing out this issue. Appreciated!
